# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"

# API and dashboard configuration
api:
  insecure: true

pilot:
    token: "60aaa714-91f1-4018-9307-7dce75193bd5"

experimental:
  localPlugins:
    traefik-authz:
      moduleName: github.com/casbin/traefik-authz
  plugins:
    example:
      moduleName: github.com/traefik/plugindemo
      version: v0.2.1